### PR TITLE
Heaps matt0704

### PR DESCRIPTION
**Pull request by mfscheidler**
merging heaps into master

### CODE REVIEW

**Comment by schultrc** [comment]
Rgr. I will be out at least thru Tuesday. Please run the meeting tomorrow
for me.

I will look at the heap stuff tomorrow am or Tuesday am.

**Comment by mfscheidler** [comment]
Sounds good--I'll take care of the meeting (probably gonna be pretty short, I imagine).  I might be on to something with the time calculation problem, but I had to stop just at the moment of eureka.  It revolves around the values moving around in the while and for loops for tmTotal; otherwise, the algo is functioning perfectly.  I compared the weights to pathrecalc and they are identical, so when we get this time problem sorted, we're done.

Stay safe out there and fight the good fight.  Let me know if you come up with anything after looking at my code.

Also, how do we switch the pathfinding algorithm with the GRIDsim code?  I'm not sure where that is.

Matt

Date: Sun, 10 Jul 2016 15:52:06 -0700

**Comment by mfscheidler** [comment]
Hey Ray

Good news: I've got time working properly, now, so we are good to go.

Take it easy,
Matt

Date: Sun, 10 Jul 2016 15:52:06 -0700

**Comment by schultrc** [comment]
I didn't get a chance to look at the merge out yet.

I will probably be sent down to Salida tomorrow to fight the Hayden fire.
I will not be at our meeting, I will send a separate email to Tom /
Farnoush.

I will attempt to look at your merge out as well as explain where to change
the algo ASAP, but may not be until Thursday or Friday. If we get sent
down, the next 48 hours will be a zoo.

-Ray

**Comment by mfscheidler** [comment]
No worries--we'll catch up when you're back.

Date: Tue, 12 Jul 2016 22:16:00 -0700

**Pull request merged**
